skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
cookie_vault = "rjHBQ3fcHKCr4VEKQjkwBtDuNZG8YCAZHmfKWfaHER5"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
